repos:
  - repo: https://github.com/chainguard-dev/pre-commit-hooks
    rev: main
    hooks:
      - id: check-for-epoch-bump

  #- repo: https://github.com/chainguard-dev/yam
  - repo: https://github.com/amberarcadia/yam
    rev: 997f75d8b0e93de6fcedd0c6c93d1ec9019dc2a8
    hooks:
      - id: yam

  #- repo: https://github.com/wolfi-dev/wolfictl
  - repo: https://github.com/amberarcadia/wolfictl
    rev: 8acdd9e21ced7e95bba4ecc0ecc78b8f97b14de0
    hooks:
      - id: wolfictl-lint
