# Update with `pre-commit autoupdate --freeze` which
# pins all repos using commit hashes, not mutable references
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # v5.0.0
    hooks:
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: forbid-submodules
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 12753357c00c3fb8615100354c9fdc6ab80b044d # frozen: v0.11.10
    hooks:
      - id: ruff-check
      - id: ruff-format
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: 79cc0ae5abfa1ba092b5938cd811a6069710ad77  # frozen: v2.8.0
    hooks:
      - id: setup-cfg-fmt
  - repo: https://github.com/asottile/reorder-python-imports
    rev: fd0b4e1292716bcd12a396b86af1d1271aaaa62c  # frozen: v3.14.0
    hooks:
      - id: reorder-python-imports
        args: [--py39-plus, --add-import, 'from __future__ import annotations']
  - repo: https://github.com/asottile/add-trailing-comma
    rev: d2e6adc1665e461a764e2f38edfa2ef61f41be20  # frozen: v3.1.0
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/asottile/pyupgrade
    rev: ce40a160603ab0e7d9c627ae33d7ef3906e2d2b2  # frozen: v3.19.1
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: f40886d54c729f533f864ed6ce584e920feb0af7  # frozen: v1.15.0
    hooks:
      - id: mypy
  - repo: https://github.com/golangci/misspell
    rev: 528d713e620bdf4b41849db93cb489c4fef9f5c5 # v0.6.0
    hooks:
      - id: misspell
        exclude: '^example\.pre-commit-config\.yaml$'
