# In general, this file should be able to be used as-is in other repos
# such as wolfi-dev/os, enterprise-packages, and extra-packages,
# and can be assumed to be the "source of truth" for our pre-commit rules.
repos:
  - repo: https://github.com/chainguard-dev/pre-commit-hooks
    rev: e4f3bba353cc583ce73f660dcf217e245fd681d3
    hooks:
      - id: check-for-epoch-bump
  # TODO: Swap with CG repo: - repo: https://github.com/chainguard-dev/yam
  - repo: https://github.com/amberarcadia/yam
    rev: 997f75d8b0e93de6fcedd0c6c93d1ec9019dc2a8
    hooks:
      - id: yam
  # TODO: Swap with CG repo: - repo: https://github.com/wolfi-dev/wolfictl
  - repo: https://github.com/amberarcadia/wolfictl
    rev: 85b1301c4d17fcd0c8f0ce455724941cae815d68
    hooks:
      - id: wolfictl-lint
  - repo: https://github.com/golangci/misspell
    rev: 528d713e620bdf4b41849db93cb489c4fef9f5c5 # v0.6.0
    hooks:
      - id: misspell
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: forbid-submodules
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
