# In general, this file (when sourced from https://github.com/chainguard-dev/pre-commit-hooks)
# should be able to be used as-is in other repos such as wolfi-dev/os, enterprise-packages, and extra-packages,
# and can be assumed to be the "source of truth" for our pre-commit rules.
# See https://eng.inky.wtf/docs/technical/git/pre-commit for info on how to edit this file.
repos:
  - repo: https://github.com/chainguard-dev/pre-commit-hooks
    rev: 71fca50bcd1006b5cbcf71f03a3b493f48c4af7f
    hooks:
      - id: check-for-epoch-bump
      - id: shellcheck-run-steps
  - repo: https://github.com/chainguard-dev/yam
    rev: 693d578a25dccd5beb548984d7a3cbda40c3af41  # frozen: v0.2.16
    hooks:
      - id: yam
  # TODO: Swap with CG repo: - repo: https://github.com/wolfi-dev/wolfictl
  - repo: https://github.com/amberarcadia/wolfictl
    rev: 85b1301c4d17fcd0c8f0ce455724941cae815d68
    hooks:
      - id: wolfictl-lint
  - repo: https://github.com/golangci/misspell
    rev: e78f9b6cd537559a24525b6ea7e182794edfd31f  # frozen: v0.7.0
    hooks:
      - id: misspell
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # v5.0.0
    hooks:
      - id: check-yaml
      - id: forbid-submodules
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
        exclude: ^ruby-3\.0/0001-ruby-3\.0\.6-openssl-patch\.patch$
